name: dev workflow

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      check:
        required: true
        type: boolean
      deploy:
        required: true
        type: boolean

jobs:
  format:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     matrix_config: ${{ fromJson(needs.generate_matrix_config.outputs.matrix) }}
    # needs: [generate_matrix_config]
    if: inputs.check
    steps:
      - uses: actions/checkout@v4
      - run: echo "execute ${{ inputs.conetxt }} format"

  build:
    runs-on: ubuntu-latest
    # needs: [generate_matrix_config, format]
    needs: [format]
    if: success() || inputs.deploy
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     matrix_config: ${{ fromJson(needs.generate_matrix_config.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "execute ${{ inputs.context }} build"