name: Release workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'commit SHA'
        required: true
        type: string

      release_tag:
        description: 'release tag'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: tag prod tag
        run: |
          git tag ${{ inputs.release_tag }} ${{ inputs.commit_sha }}
          git push origin ${{ inputs.release_tag }}
