name: Release workflow

on:
  workflow_dispatch:
    inputs:
      rc_tag:
        description: 'tag name'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check rc tag exist
        run: echo "check rc tag ${{ inputs.rc_tag }} exist"

      - name: tag prod tag
        run: |
          git tag prod-2025-03-22-01
          git push origin prod-2025-03-22-01

      - name: release to cloud run service
        run: echo "release to cloud run service"

