name: development stage workflow

on:
  push:
    branches:
      - "*/*"
      - "!main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [app-a]

    steps:
      - uses: actions/checkout@v4

      - id: deploy
        run: echo "deploy ${{ matrix.context }} success"
