name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: print
        run: |
          echo "GITHUB_EVENT_HEAD=${{ github.event.head }}"
          echo "GITHUB_EVENT_AFTER=${{ github.event.after }}"

      # - name: Set up Google Cloud Auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     project_id: river-surf-289011
      #     credentials_json: ${{ secrets.TEST_GCP_KEY }}

      # - name: Set up Google Cloud Auth
      #   uses: ./.github/actions/build_env
      #   with:
      #     gcp_key: ${{ secrets.TEST_GCP_KEY }}
