name: test manual workflow ${{ inputs.branch_name }}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch name'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch_name }}

      - id: deploy
        run: echo "trigger deploy at ${{ inputs.branch_name }} branch"
