name: Cleanup After Merge Pull Request

on:
  delete

jobs:
  generate_context_config:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      # - name: Check if delete is for tag
      #   if: github.event.ref_type == 'tag'
      #   run: |
      #     echo "Skipping because this is a tag deletion"
      #     exit 0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get_git_diff_base_sha
        name: Get git diff base SHA
        run: |
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GIT_MERGE_BASE_WITH_MAIN=$(git merge-base ${GITHUB_REF#refs/heads/} origin/main)"
          echo "GITHUB_EVENT_BEFORE=${{ github.event.before }}"
          echo "GITHUB_EVENT_AFTER=${{ github.event.after }}"
          echo "GITHUB_EVENT_REF=${{ github.event.ref }}"
          echo "GITHUB_EVENT_REF_TYPE=${{ github.event.ref_type }}"

  cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    needs: [generate_context_config]

    steps:
      - name: Delete
        run: echo "delete resource"
